-- ============================================================================
-- REVENUE VISIBILITY PERMISSIONS
-- ============================================================================
--
-- Business-wide revenue and personal revenue are separate permissions.
-- Operators get only personal revenue by default. Managers and owners get both.

INSERT INTO public.permissions (key, module_key, action, description) VALUES
  ('reports.view_business_revenue', 'reports', 'view_business_revenue', 'View business-wide revenue metrics and trends'),
  ('reports.view_personal_revenue', 'reports', 'view_personal_revenue', 'View revenue generated by the current user')
ON CONFLICT (key) DO NOTHING;

INSERT INTO public.role_permissions (role, permission_key)
VALUES
  ('owner',   'reports.view_business_revenue'),
  ('owner',   'reports.view_personal_revenue'),
  ('manager', 'reports.view_business_revenue'),
  ('manager', 'reports.view_personal_revenue'),
  ('staff',   'reports.view_personal_revenue')
ON CONFLICT (role, permission_key) DO NOTHING;

DO $$
DECLARE
  v_sales_op_id     uuid;
  v_service_op_id   uuid;
  v_rental_op_id    uuid;
  v_ops_mgr_id      uuid;
  v_biz_mgr_id      uuid;
  v_owner_id        uuid;
BEGIN
  SELECT id INTO v_sales_op_id   FROM public.permission_profiles WHERE name = 'Sales Operator'      AND business_id IS NULL;
  SELECT id INTO v_service_op_id FROM public.permission_profiles WHERE name = 'Service Operator'    AND business_id IS NULL;
  SELECT id INTO v_rental_op_id  FROM public.permission_profiles WHERE name = 'Rental Operator'     AND business_id IS NULL;
  SELECT id INTO v_ops_mgr_id    FROM public.permission_profiles WHERE name = 'Operations Manager'  AND business_id IS NULL;
  SELECT id INTO v_biz_mgr_id    FROM public.permission_profiles WHERE name = 'Business Manager'    AND business_id IS NULL;
  SELECT id INTO v_owner_id      FROM public.permission_profiles WHERE name = 'Owner'               AND business_id IS NULL;

  IF v_sales_op_id IS NOT NULL THEN
    INSERT INTO public.permission_profile_grants (profile_id, permission_key, scope)
    VALUES
      (v_sales_op_id, 'reports.view', 'own'),
      (v_sales_op_id, 'reports.view_personal_revenue', 'own')
    ON CONFLICT (profile_id, permission_key) DO UPDATE SET scope = 'own';
  END IF;

  IF v_service_op_id IS NOT NULL THEN
    INSERT INTO public.permission_profile_grants (profile_id, permission_key, scope)
    VALUES
      (v_service_op_id, 'reports.view', 'assigned'),
      (v_service_op_id, 'reports.view_personal_revenue', 'assigned')
    ON CONFLICT (profile_id, permission_key) DO UPDATE SET scope = EXCLUDED.scope;
  END IF;

  IF v_rental_op_id IS NOT NULL THEN
    INSERT INTO public.permission_profile_grants (profile_id, permission_key, scope)
    VALUES
      (v_rental_op_id, 'reports.view', 'own'),
      (v_rental_op_id, 'reports.view_personal_revenue', 'own')
    ON CONFLICT (profile_id, permission_key) DO UPDATE SET scope = 'own';
  END IF;

  IF v_ops_mgr_id IS NOT NULL THEN
    INSERT INTO public.permission_profile_grants (profile_id, permission_key, scope) VALUES
      (v_ops_mgr_id, 'reports.view_personal_revenue', 'all'),
      (v_ops_mgr_id, 'reports.view_business_revenue', 'all')
    ON CONFLICT (profile_id, permission_key) DO UPDATE SET scope = EXCLUDED.scope;
  END IF;

  IF v_biz_mgr_id IS NOT NULL THEN
    INSERT INTO public.permission_profile_grants (profile_id, permission_key, scope) VALUES
      (v_biz_mgr_id, 'reports.view_personal_revenue', 'all'),
      (v_biz_mgr_id, 'reports.view_business_revenue', 'all')
    ON CONFLICT (profile_id, permission_key) DO UPDATE SET scope = EXCLUDED.scope;
  END IF;

  IF v_owner_id IS NOT NULL THEN
    INSERT INTO public.permission_profile_grants (profile_id, permission_key, scope) VALUES
      (v_owner_id, 'reports.view_personal_revenue', 'all'),
      (v_owner_id, 'reports.view_business_revenue', 'all')
    ON CONFLICT (profile_id, permission_key) DO UPDATE SET scope = EXCLUDED.scope;
  END IF;
END;
$$;
